spring.config.import=optional:file:.env[.properties]





# MongoDB Atlas Connection
spring.mongodb.uri=${MONGO_URI}


server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=true